name: Main CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    name: Build and SonarCloud Analyze
    runs-on: ubuntu-latest

    steps:
      # 1. Kodu çek
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. .NET ortamını kur
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Projene göre 6.0 veya 7.0 da olabilir

      # 3. Bağımlılıkları yükle
      - name: Restore dependencies
        run: dotnet restore

      # 4. Projeyi derle
      - name: Build
        run: dotnet build --no-restore

      # 5. SonarCloud analizi yap
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=codeby-nurgul
            -Dsonar.projectKey=dotnet-sample
            -Dsonar.projectName=dotnet-sample
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
